name: Generate Text File
on: [workflow_dispatch]
jobs:
  generate_text_file:
    runs-on: ubuntu-latest
    steps:
      - name: Create Text File
        run: echo "fifth test" > hello.txt
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: hello-text
          path: hello.txt
      - name: echo run number
        run: echo ${{ github.run_number }}
  upload-to-s3:
    uses: ./.github/workflows/upload-to-s3.yml
    with: 
      workflow-name: generate-file.yml
      run-number: ${{ github.run_number }}
    secrets: inherit  
    needs: generate_text_file