name: Generate Text File
on: [workflow_dispatch]
jobs:
  generate_text_file:
    runs-on: ubuntu-latest
    steps:
      - name: Create Text File
        run: echo "hello world" > hello.txt
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: hello-text
          # path: hello.txt
