name: Generate Text File
on: [workflow_dispatch]
jobs:
  generate_text_file:
    runs-on: ubuntu-latest
    steps:
      - name: Create Text File
        run: echo "more test" > hello.txt
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: hello.txt
  upload-to-s3:
    uses: ./.github/workflows/upload-to-s3.yml
    with:
      workflow-name: generate-file.yml
    secrets: inherit
    needs: generate_text_file
