name: Generate Text File
on: [workflow_dispatch]
jobs:
  generate_text_file:
    runs-on: ubuntu-latest
    steps:
      - name: Create Text File
        run: echo "hello world" > hello.txt
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: hello-text
          path: hello.txt
  upload-to-s3:
    uses: ./.github/workflows/upload-to-s3.yml
    with: 
      workflow-name: ${{ github.workflow }} 
    # runs-on: ubuntu-latest
    # steps:
    #   - name: Upload to s3
    #     uses: dan-german/blocks/.github/workflows/upload-to-s3.yml@main
    #     with: 
    #       workflow-name: ${{ github.workflow }}
