name: Upload to S3
on: workflow_call
jobs:
  upload-to-s3:
    runs-on: ubuntu-latest
    steps:
      - name: pwd
        run: pwd
      - name: Download build-output artifact
        uses: actions/download-artifact@v4
        # with: 
        #   name: blocks/files 
      - name: Upload to S3
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: "blocksbucket"
          source_dir: "./"
          destination_dir: "./"
