name: Upload to S3
on: 
  workflow_call:
    inputs: 
      file-name: 
        required: true
        type: string
jobs:
  upload-to-s3:
    runs-on: ubuntu-latest
    steps:
      - name: pwd
        run: pwd
      - name: Download build-output artifact
        uses: actions/download-artifact@v4
        # with: 
        #   path: files
        #   name: ${{ inputs.file-name }}
      - name: ls
        run: ls
      - name: zip
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r ${{ inputs.file-name }}.zip ${{ inputs.file-name }}
      - name: Upload to S3
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: "blocksbucket"
          source_dir: "./"
          destination_dir: "./"
